/**
 * Terrain mesh utilities
 * 
 * Helper functions for working with terrain generation data
 */

/**
 * Convert terrain mesh data to OBJ format string
 * 
 * Takes raw vertex, color, and face data from TerrainHandle
 * and converts it to OBJ format that can be loaded by the viewer.
 * 
 * @param vertices - Flattened vertex positions [x, y, z, x, y, z, ...]
 * @param colors - Flattened vertex colors [r, g, b, r, g, b, ...]
 * @param faces - Triangle indices [i0, i1, i2, i0, i1, i2, ...]
 * @returns OBJ format string
 */
export function meshDataToObj(
    vertices: Float32Array,
    colors: Float32Array,
    faces: Uint32Array
): string {
    const lines: string[] = [];
    
    // Write header
    lines.push('# Generated by PolyLab Terrain');
    lines.push('# Procedural terrain mesh');
    lines.push('');
    
    // Write vertices with colors
    // OBJ format: v x y z [r g b]
    const numVertices = vertices.length / 3;
    for (let i = 0; i < numVertices; i++) {
        const vx = vertices[i * 3];
        const vy = vertices[i * 3 + 1];
        const vz = vertices[i * 3 + 2];
        
        const r = colors[i * 3];
        const g = colors[i * 3 + 1];
        const b = colors[i * 3 + 2];
        
        lines.push(`v ${vx} ${vy} ${vz} ${r} ${g} ${b}`);
    }
    
    lines.push('');
    
    // Write faces
    // OBJ format: f i1 i2 i3 (1-indexed)
    const numFaces = faces.length / 3;
    for (let i = 0; i < numFaces; i++) {
        const i0 = faces[i * 3] + 1;     // +1 because OBJ is 1-indexed
        const i1 = faces[i * 3 + 1] + 1;
        const i2 = faces[i * 3 + 2] + 1;
        
        lines.push(`f ${i0} ${i1} ${i2}`);
    }
    
    return lines.join('\n');
}

/**
 * Terrain generation statistics
 */
export interface TerrainStats {
    num_vertices: number;
    num_faces: number;
    min_height: number;
    max_height: number;
    avg_height: number;
}

/**
 * Result of terrain generation
 */
export interface TerrainGenerationResult {
    vertices: Float32Array;
    colors: Float32Array;
    faces: Uint32Array;
    heightmap: Float32Array;
    slope_map?: Float32Array;
    stats: TerrainStats;
}
