[package]
name = "polylab-viewer"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
polylab-core = { path = "../polylab-core" }
glam = { workspace = true }
wgpu = "29.0"
pollster = "0.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = [
    "Document",
    "Window",
    "Element",
    "HtmlCanvasElement",
] }
console_error_panic_hook = "0.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
winit = "0.30"

[lib]
crate-type = ["cdylib", "rlib"]
