// PolyLab Web App Entry Point
import { Header } from './components/Header';
import { Toolbar } from './components/Toolbar';
import { MeshPanel } from './components/MeshPanel';
import { DetailsPanel } from './components/DetailsPanel';
import { StatusBar } from './components/StatusBar';
import { ViewerCanvas } from './components/ViewerCanvas';

// Import styles
import './styles/main.css';
import './styles/header.css';
import './styles/toolbar.css';
import './styles/panels.css';
import './styles/statusbar.css';

/**
 * Initialize the UI components
 */
function initializeUI() {
    const app = document.getElementById('app')!;
    
    // Create components
    const header = new Header();
    const toolbar = new Toolbar();
    const meshPanel = new MeshPanel();
    const viewerCanvas = new ViewerCanvas();
    const detailsPanel = new DetailsPanel();
    const statusBar = new StatusBar();

    // Build layout
    const mainContent = document.createElement('div');
    mainContent.className = 'main-content';
    
    mainContent.appendChild(meshPanel.element);
    mainContent.appendChild(viewerCanvas.element);
    mainContent.appendChild(detailsPanel.element);

    app.appendChild(header.element);
    app.appendChild(toolbar.element);
    app.appendChild(mainContent);
    app.appendChild(statusBar.element);

    return {
        header,
        toolbar,
        meshPanel,
        viewerCanvas,
        detailsPanel,
        statusBar
    };
}

/**
 * Initialize WebGPU viewer
 */
async function initializeViewer(canvas: HTMLCanvasElement, statusBar: StatusBar) {
    try {
        statusBar.updateStats({ status: 'Loading WebAssembly module...' });

        // Import the WASM module (generated by wasm-pack)
        const wasmModule = await import('../../../crates/polylab-viewer/pkg/polylab_viewer.js');
        await wasmModule.default();

        statusBar.updateStats({ status: 'Creating viewer...' });

        // Create viewer instance
        const viewer = await wasmModule.ViewerHandle.create('webgpu-canvas');

        statusBar.updateStats({ 
            status: '✅ Rendering!',
            backend: 'WebGPU'
        });

        // FPS counter
        let frameCount = 0;
        let lastTime = performance.now();

        // Animation loop
        function animate() {
            try {
                viewer.render();
                
                // Update FPS
                frameCount++;
                const currentTime = performance.now();
                if (currentTime - lastTime >= 1000) {
                    const fps = Math.round(frameCount * 1000 / (currentTime - lastTime));
                    statusBar.updateStats({ fps });
                    frameCount = 0;
                    lastTime = currentTime;
                }

                requestAnimationFrame(animate);
            } catch (e) {
                console.error('Render error:', e);
                statusBar.updateStats({ status: `❌ Error: ${e}` });
            }
        }

        animate();

        console.log('[PolyLab] Viewer initialized successfully');

    } catch (error) {
        console.error('Failed to initialize:', error);
        statusBar.updateStats({ status: `❌ Error: ${error}` });

        // Check if WebGPU is supported
        if (!navigator.gpu) {
            statusBar.updateStats({ 
                status: '❌ WebGPU not supported. Use Chrome 113+ or Edge 113+' 
            });
        }
    }
}

/**
 * Main application entry point
 */
async function main() {
    // Check WebGPU support
    if (!navigator.gpu) {
        alert('❌ WebGPU is not supported in this browser.\n\nPlease use:\n- Chrome 113+\n- Edge 113+\n- Firefox Nightly with WebGPU enabled');
        return;
    }

    // Initialize UI
    const ui = initializeUI();
    console.log('[PolyLab] UI initialized');

    // Initialize WebGPU viewer
    const canvas = ui.viewerCanvas.getCanvas();
    
    // Auto-resize canvas to fit container
    ui.viewerCanvas.autoResize();
    
    await initializeViewer(canvas, ui.statusBar);
}

// Start the application
main();

