// PolyLab Web App Entry Point
import { Header } from './components/Header';
import { Toolbar } from './components/Toolbar';
import { MeshPanel } from './components/MeshPanel';
import { DetailsPanel } from './components/DetailsPanel';
import { StatusBar } from './components/StatusBar';
import { ViewerCanvas } from './components/ViewerCanvas';

// Import styles
import './styles/main.css';
import './styles/header.css';
import './styles/toolbar.css';
import './styles/panels.css';
import './styles/statusbar.css';

/**
 * Initialize the UI components
 */
function initializeUI() {
    const app = document.getElementById('app')!;
    
    // Create components
    const header = new Header();
    const toolbar = new Toolbar();
    const meshPanel = new MeshPanel();
    const viewerCanvas = new ViewerCanvas();
    const detailsPanel = new DetailsPanel();
    const statusBar = new StatusBar();

    // Build layout
    const mainContent = document.createElement('div');
    mainContent.className = 'main-content';
    
    mainContent.appendChild(meshPanel.element);
    mainContent.appendChild(viewerCanvas.element);
    mainContent.appendChild(detailsPanel.element);

    app.appendChild(header.element);
    app.appendChild(toolbar.element);
    app.appendChild(mainContent);
    app.appendChild(statusBar.element);

    return {
        header,
        toolbar,
        meshPanel,
        viewerCanvas,
        detailsPanel,
        statusBar
    };
}

/**
 * Initialize WebGPU viewer
 * 
 * @returns The viewer handle for interaction
 */
async function initializeViewer(canvas: HTMLCanvasElement, statusBar: StatusBar) {
    try {
        statusBar.updateStats({ status: 'Loading WebAssembly module...' });

        // Import the WASM module (generated by wasm-pack)
        const wasmModule = await import('../../../crates/polylab-viewer/pkg/polylab_viewer.js');
        await wasmModule.default();

        statusBar.updateStats({ status: 'Creating viewer...' });

        // Create viewer instance
        const viewer = await wasmModule.ViewerHandle.create('webgpu-canvas');

        statusBar.updateStats({ 
            status: '✅ Rendering!',
            backend: 'WebGPU'
        });

        // FPS counter
        let frameCount = 0;
        let lastTime = performance.now();

        // Animation loop
        function animate() {
            try {
                viewer.render();
                
                // Update FPS
                frameCount++;
                const currentTime = performance.now();
                if (currentTime - lastTime >= 1000) {
                    const fps = Math.round(frameCount * 1000 / (currentTime - lastTime));
                    statusBar.updateStats({ fps });
                    frameCount = 0;
                    lastTime = currentTime;
                }

                requestAnimationFrame(animate);
            } catch (e) {
                console.error('Render error:', e);
                statusBar.updateStats({ status: `❌ Error: ${e}` });
            }
        }

        animate();

        console.log('[PolyLab] Viewer initialized successfully');

        // Return viewer handle for mesh loading
        return viewer;

    } catch (error) {
        console.error('Failed to initialize:', error);
        statusBar.updateStats({ status: `❌ Error: ${error}` });

        // Check if WebGPU is supported
        if (!navigator.gpu) {
            statusBar.updateStats({ 
                status: '❌ WebGPU not supported. Use Chrome 113+ or Edge 113+' 
            });
        }
        
        throw error;
    }
}

/**
 * Main application entry point
 */
async function main() {
    // Check WebGPU support
    if (!navigator.gpu) {
        alert('❌ WebGPU is not supported in this browser.\n\nPlease use:\n- Chrome 113+\n- Edge 113+\n- Firefox Nightly with WebGPU enabled');
        return;
    }

    // Initialize UI
    const ui = initializeUI();
    console.log('[PolyLab] UI initialized');

    // Initialize WebGPU viewer
    const canvas = ui.viewerCanvas.getCanvas();
    
    // Auto-resize canvas to fit container
    ui.viewerCanvas.autoResize();
    
    try {
        const viewer = await initializeViewer(canvas, ui.statusBar);

        // Initialize DetailsPanel with default triangle info
        const initialDetails = viewer.mesh_details(null);
        const [initVertices, initTriangles, initSizeX, initSizeY, initSizeZ] = initialDetails;
        ui.detailsPanel.updateDetails({
            vertices: Math.round(initVertices),
            triangles: Math.round(initTriangles),
            sizeX: initSizeX,
            sizeY: initSizeY,
            sizeZ: initSizeZ
        });

        // Set up visibility toggle callback for all meshes
        ui.meshPanel.setVisibilityCallback((id: string, visible: boolean) => {
            viewer.set_mesh_visibility(id, visible);
            console.log(`[PolyLab] Mesh ${id} visibility: ${visible}`);
        });

        // Setup mesh loading callbacks
        ui.toolbar.setLoadCallback(
            // onLoad callback
            async (objContent: string, filename: string) => {
                try {
                    ui.statusBar.updateStats({ status: `Loading ${filename}...` });
                    
                    // Generate unique mesh ID
                    const meshId = `mesh-${Date.now()}`;
                    
                    // Call WASM function to load mesh
                    viewer.load_mesh(meshId, objContent);
                    
                    // Get detailed mesh info from viewer
                    const details = viewer.mesh_details(meshId);
                    const [vertices, triangles, sizeX, sizeY, sizeZ] = details;
                    
                    // Add mesh to MeshPanel with visibility callback
                    ui.meshPanel.addMesh({
                        id: meshId,
                        name: filename,
                        vertices: Math.round(vertices),
                        triangles: Math.round(triangles),
                        visible: true
                    });
                    
                    // Update DetailsPanel with dimensions
                    ui.detailsPanel.updateDetails({
                        vertices: Math.round(vertices),
                        triangles: Math.round(triangles),
                        sizeX,
                        sizeY,
                        sizeZ
                    });
                    
                    // Update status bar
                    ui.statusBar.updateStats({ 
                        status: `✅ Loaded ${filename}`,
                        vertices: Math.round(vertices),
                        triangles: Math.round(triangles)
                    });
                    
                    console.log(`[PolyLab] Loaded mesh: ${Math.round(vertices)} vertices, ${Math.round(triangles)} triangles, size: [${sizeX.toFixed(2)}, ${sizeY.toFixed(2)}, ${sizeZ.toFixed(2)}]`);
                } catch (error) {
                    const errorMsg = error instanceof Error ? error.message : String(error);
                    ui.statusBar.updateStats({ status: `❌ ${errorMsg}` });
                    console.error('[PolyLab] Mesh loading error:', error);
                }
            },
            // onError callback
            (error: string) => {
                ui.statusBar.updateStats({ status: `❌ ${error}` });
                console.error('[PolyLab] File loading error:', error);
            }
        );

        console.log('[PolyLab] Mesh loading configured');
    } catch (error) {
        console.error('[PolyLab] Failed to initialize viewer:', error);
    }
}

// Start the application
main();

